"""
URL configuration for chat app.
"""
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('setup/', views.setup_wizard, name='setup'),
    path('chat/', views.chat, name='chat'),
    path('chat/new/', views.new_chat, name='new_chat'),
    path('chat/start/', views.start_chat, name='start_chat'),
    path('chat/switch/', views.switch_session, name='switch_session'),
    path('chat/delete/', views.delete_chat, name='delete_chat'),
    path('chat/pin/', views.toggle_pin_chat, name='toggle_pin_chat'),
    path('chat/rename/', views.rename_chat, name='rename_chat'),
    path('chat/save-draft/', views.save_draft, name='save_draft'),
    path('chat/send/', views.send_message, name='send_message'),
    path('memory/', views.memory, name='memory'),
    path('memory/update/', views.update_memory, name='update_memory'),
    path('memory/wipe/', views.wipe_memory, name='wipe_memory'),
    path('memory/modify/', views.modify_memory, name='modify_memory'),
    path('memory/save-settings/', views.save_memory_settings, name='save_memory_settings'),
    path('memory/context/upload/', views.upload_context_file, name='upload_context_file'),
    path('memory/context/delete/', views.delete_context_file, name='delete_context_file'),
    path('memory/context/toggle/', views.toggle_context_file, name='toggle_context_file'),
    path('memory/context/content/', views.get_context_file_content, name='get_context_file_content'),
    path('memory/context/save/', views.save_context_file_content, name='save_context_file_content'),
    path('persona/', views.persona_settings, name='persona_settings'),
    path('persona/context/upload/', views.upload_persona_context_file, name='upload_persona_context_file'),
    path('persona/context/delete/', views.delete_persona_context_file, name='delete_persona_context_file'),
    path('persona/context/toggle/', views.toggle_persona_context_file, name='toggle_persona_context_file'),
    path('persona/context/content/', views.get_persona_context_file_content, name='get_persona_context_file_content'),
    path('persona/context/save/', views.save_persona_context_file_content, name='save_persona_context_file_content'),
    path('settings/', views.settings, name='settings'),
    path('settings/save/', views.save_settings, name='save_settings'),
    path('settings/validate-api-key/', views.validate_provider_api_key, name='validate_provider_api_key'),
    path('settings/save-provider-model/', views.save_provider_model, name='save_provider_model'),
    path('settings/save-context-history-limit/', views.save_context_history_limit, name='save_context_history_limit'),
    path('settings/available-models/', views.get_available_models, name='get_available_models'),
    path('settings/save-persona/', views.save_persona_file, name='save_persona_file'),
    path('settings/create-persona/', views.create_persona, name='create_persona'),
    path('settings/delete-persona/', views.delete_persona, name='delete_persona'),
    path('settings/save-persona-model/', views.save_persona_model, name='save_persona_model'),
    path('api/themes/', views.get_available_themes, name='get_themes'),
    path('api/save-theme/', views.save_theme, name='save_theme'),
]
